apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubetask.fullname" . }}-config
  labels:
    {{- include "kubetask.labels" . | nindent 4 }}
data:
  config.yaml: |
    log-level: {{ .Values.config.logLevel }}
    log-format: {{ .Values.config.logFormat }}
    api-port: {{ .Values.api.port }}
    api-host: {{ .Values.api.host }}
